image: docker:20.10.22

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  REDIS_PORT: 6379

services:
  - docker:20.10.22-dind
  

stages:
  - preparation
  - build
  - deploy

cache:
  paths:
    - vendor/

composer:
  image: php:8.2.2
  services:
    - redis:7.0.8
  stage: preparation
  script:
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    # - php artisan key:generate
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

build image:
  stage: build
  before_script:
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_BRANCH
    - echo $CI_COMMIT_TAG
    - echo $CI_PROJECT_DIR
    - whoami
    - |
      for i in $(seq 1 30)
      do
          docker info && break
          echo "Waiting for docker to start"
          sleep 3s
      done
  script:
    - PROJECT_TITLE=$(echo $CI_PROJECT_TITLE | tr A-Z a-z)
    - docker build -t ${PROJECT_TITLE}:latest .
    - docker push ${PROJECT_TITLE}:latest

helm deploy:
  stage: deploy
  image:
    name: mshahmalaki/swiss-knife:1.1.2
  before_script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
  script:
    - |
      helm upgrade --install --create-namespace --namespace infra-test redis bitnami/redis
      --set-string auth.password=qwerty1234
    - |
      helm upgrade --install --create-namespace --namespace infra-test infra-test chart
      --set-string redis.password=${REDIS_PASSWORD}