apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "chart.name" .) }}
  namespace: {{ .Release.Namespace | quote }}
data:
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PASSWORD: {{ .Values.redis.password }}
  REDIS_PORT: {{ .Values.redis.port | quote }}